option('pro-build', type: 'boolean', value : false, description: 'Enable Dovecot Pro')
option('moduledir', type: 'string', value : '', description: 'Base directory for dynamically loadable modules')
option('development-extra-checks', type: 'combo', choices: ['no', 'fast', 'yes'], value: 'no', description: 'Enable some extra expensive checks for developers (fast enables only some of them)')
option('development-static-analysis', type: 'boolean', value: false, description: 'Enable code to be used when building with static code analyzer')
option('experimental-mail-utf8', type: 'boolean', value: false, description: 'Enable experimental support for SMTPUTF8 and UTF8=ACCEPT')
option('hardening', type: 'boolean', value: true, description: 'Enable various code hardening features')
option('hardening-retpoline', type: 'combo', choices: ['none', 'keep', 'thunk', 'thunk-inline', 'thunk-extern'], value: 'keep', description: 'Retpoline mitigation choice')
option('hardening-fcf-protection', type: 'combo', choices: ['none', 'branch', 'return', 'full'], value: 'none', description: 'Control-flow protection level')
option('hardening-sls', type: 'combo', choices: ['none', 'all', 'return', 'indirect-jmp'], value: 'none', description: 'Straight-Line Speculation (SLS) mitigation choice')
option('hardening-stack-protector', type: 'combo', choices: ['off', 'auto', 'normal', 'strong'], value: 'auto', description: 'Add stack guards for buffer overflows')
option('libbsd', type: 'feature', value: 'disabled', description: 'Use libbsd for arc4random() and setproctitle()')
option('mem-align', type: 'integer', value: 8, min: 1, description: 'Set the memory alignment')
option('random-source', type: 'string', value : '/dev/urandom', description: 'Device file to use as random source')
option('ioloop', type: 'combo', choices: ['best', 'epoll', 'kqueue', 'poll', 'select'], value: 'best', description: 'I/O loop method to use (best for the fastest available)')
option('notify', type: 'combo', choices: ['best', 'inotify', 'kqueue', 'none'], value: 'best', description: 'File system notification method to use (best for the fastest available)')
option('sodium', type: 'feature', value: 'auto', description: 'Build with libsodium support (enables argon2)')
option('pcre', type: 'feature', value: 'auto', description: 'Build with libpcre2 support (enables regular expressions)')
option('gssapi', type: 'combo', choices: ['disabled', 'enabled', 'auto', 'plugin'], value: 'disabled', description: 'Build with GSSAPI authentication support')
