option('pro-build', type: 'boolean', value : false, description: 'Enable Dovecot Pro')
option('moduledir', type: 'string', value : '', description: 'Base directory for dynamically loadable modules')
option('development-extra-checks', type: 'combo', choices: ['no', 'fast', 'yes'], value: 'no', description: 'Enable some extra expensive checks for developers (fast enables only some of them)')
option('development-static-analysis', type: 'boolean', value: false, description: 'Enable code to be used when building with static code analyzer')
option('experimental-mail-utf8', type: 'boolean', value: false, description: 'Enable experimental support for SMTPUTF8 and UTF8=ACCEPT')
