#!/bin/sh
set -e

. /usr/share/debconf/confmodule

MDA_CONF_DIR=/etc/dovecot
MDA_CONF_ENV=$MDA_CONF_DIR/conf.d/00-environment.conf

read_params_debconf()
{
    db_get r7mdaserver/mda-doveadm-key || true
    MDA_API_KEY="${RET:-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 32)}"

    db_get r7mdaserver/mda-ssl-cert || true
    MDA_CERT_FILENAME="$(realpath -m "$RET" 2>/dev/null)"
    db_get r7mdaserver/mda-ssl-key || true
    MDA_KEY_FILENAME="$(realpath -m "$RET" 2>/dev/null)"
    db_get r7mdaserver/mda-dh-key || true
    MDA_DH_FILENAME="$(realpath -m "$RET" 2>/dev/null)"

    db_get r7mailfrontend/db-host || true
    MDA_DB_HOST="${RET:-localhost}"
    db_get r7mailfrontend/db-port || true
    MDA_DB_PORT="${RET:-5432}"
	db_get r7mailfrontend/db-name || true
    MDA_DB_NAME="${RET:-r7mailserver}"
    db_get r7mailfrontend/db-user || true
    MDA_DB_USER="${RET:-r7mailuser}"
    db_get r7mailfrontend/db-pwd || true
    MDA_DB_PWD="${RET:-saSA123$}"
#    db_get r7mailserver/upgrade
#    UPGRADE="$RET"
#    echo "ADMIN_NAME: $ADMIN_NAME"
#    echo "SITE_DOMAIN: $SITE_DOMAIN"
#    echo "API_CERT_FILENAME: $API_CERT_FILENAME"
#    echo "API_KEY_FILENAME: $API_KEY_FILENAME"
#    echo "API_ENDPOINT: $API_ENDPOINT"
#    echo "API_FILTER_ENDPOINT: $API_FILTER_ENDPOINT"
}

conf_cert()
{
#	MDA_CONF_SSL=$MDA_CONF_DIR/conf.d/10-ssl.conf
	if [ -f "$MDA_CERT_FILENAME" ] && [ -f "$MDA_KEY_FILENAME" ] && [ -f "$MDA_DH_FILENAME" ]; then
        cp "$MDA_CERT_FILENAME" "$MDA_CONF_DIR/ssl/$(basename "$MDA_CERT_FILENAME")"
        cp "$MDA_KEY_FILENAME" "$MDA_CONF_DIR/ssl/$(basename "$MDA_KEY_FILENAME")"
		cp "$MDA_DH_FILENAME" "$MDA_CONF_DIR/ssl/$(basename "$MDA_DH_FILENAME")"
    else
        echo "key or cert not found. generate certificate..."
        MDA_KEY_FILENAME=$MDA_CONF_DIR/ssl/temp-cert.pem
        MDA_CERT_FILENAME=$MDA_CONF_DIR/ssl/temp-key.pem
		MDA_DH_FILENAME=$MDA_CONF_DIR/ssl/dhparam.pem
        openssl genrsa -out "$MDA_KEY_FILENAME" 2048
        openssl req -new -x509 -key "$MDA_KEY_FILENAME" -out "$MDA_CERT_FILENAME" -days 365 -subj "/C=RU/ST=Moscow/L=Moscow/O=Company/CN=localhost"
		openssl dhparam -dsaparam -out $MDA_DH_FILENAME 2048
    fi
    chmod 644 "$MDA_CERT_FILENAME"
    chmod 600 "$MDA_KEY_FILENAME"
	chmod 600 "$MDA_DH_FILENAME"

	sed -i "s#{{ MDA_SSL_CERT }}#$MDA_CERT_FILENAME#g" $MDA_CONF_ENV
	sed -i "s#{{ MDA_SSL_KEY }}#$MDA_KEY_FILENAME#g" $MDA_CONF_ENV
	sed -i "s#{{ MDA_DH_KEY }}#$MDA_DH_FILENAME#g" $MDA_CONF_ENV
}

conf_db()
{
#	MDA_CONF_DB=$MDA_CONF_DIR/conf.d/10-pgsql.conf
	sed -i "s#{{ MDA_DB_HOST }}#$MDA_DB_HOST#g" $MDA_CONF_ENV
	sed -i "s#{{ MDA_DB_PORT }}#$MDA_DB_PORT#g" $MDA_CONF_ENV
	sed -i "s#{{ MDA_DB_NAME }}#$MDA_DB_NAME#g" $MDA_CONF_ENV
	sed -i "s#{{ MDA_DB_USER }}#$MDA_DB_USER#g" $MDA_CONF_ENV
	sed -i "s#{{ MDA_DB_PWD }}#$MDA_DB_PWD#g" $MDA_CONF_ENV
}


conf_api()
{
#	MDA_CONF_API=$MDA_CONF_DIR/conf.d/20-doveadm.conf
	sed -i "s#{{ MDA_DOVEADM_KEY }}#$MDA_API_KEY#g" $MDA_CONF_ENV
}

if [ "$1" = "configure" ]; then
  CONFFILES="dovecot.conf \
    conf.d/20-doveadm.conf"

#  CONFFILES="dovecot.conf \
#    conf.d/10-auth.conf \
#    conf.d/10-logging.conf \
#    conf.d/10-pgsql.conf \
#    conf.d/10-ssl.conf \
#    conf.d/20-doveadm.conf \
#    conf.d/20-lmtp.conf \
#    conf.d/90-acl.conf \
#    conf.d/90-notify.conf \
#    conf.d/90-quota.conf \
#    conf.d/10-mail.conf \
#    conf.d/10-protocols.conf \
#    conf.d/15-mailboxes.conf \
#    conf.d/20-imap.conf \
#    conf.d/20-managesieve.conf \
#    conf.d/90-dict.conf \
#    conf.d/90-plugin.conf \
#    conf.d/90-sieve.conf"

  ## Users
  #

  	adduser --system --group --home /opt/r7mdaserver/usr/lib/dovecot --gecos "Dovecot mail server" \
        --no-create-home --disabled-password --quiet dovecot || true

  	adduser --system --group --home /nonexistent --no-create-home --gecos "Dovecot login user" \
        --disabled-password --quiet dovenull || true

  	for conffile in $CONFFILES ; do
    # Tell ucf that the file in /opt/dovecot/usr/share/dovecot is the latest
    # maintainer version, and let it handle how to manage the real
    # configuration file in /etc/dovecot.
    	ucf --three-way "/opt/r7mdaserver/etc/dovecot/$conffile" "/etc/dovecot/$conffile"
	    ucfr r7mdaserver "/etc/dovecot/$conffile"
    	if [ "$conffile" != "dovecot.conf" ] && [ -f "/etc/dovecot/$conffile" ] && [ "$(echo "$conffile" | cut -b -7)" != "conf.d/" ]; then
      		chmod 0640 "/etc/dovecot/$conffile"
      		chgrp dovecot "/etc/dovecot/$conffile"
    	fi
  	done
	
	read_params_debconf
	conf_cert
	conf_db
	conf_api

  	if ! dpkg-statoverride --list /etc/dovecot/private >/dev/null; then
    	dpkg-statoverride --quiet --update --add root root 0700 /etc/dovecot/private
  	fi
fi

# End automatically added section
# Automatically added by dh_installsystemd/13.11.4+b4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'dovecot.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'dovecot.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'dovecot.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'dovecot.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4+b4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'dovecot.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4+b4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'dovecot.socket'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'dovecot.socket' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'dovecot.socket'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'dovecot.socket' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'dovecot.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4+b4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'dovecot.socket' >/dev/null || true
	fi
fi
# End automatically added section

