#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.11.4+b4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'dovecot.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4+b4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'dovecot.service' >/dev/null || true
fi
# End automatically added section
