subdir('lib-test')
subdir('lib')
subdir('lib-regex')
subdir('lib-var-expand')
subdir('lib-dns')
subdir('lib-settings')
subdir('lib-auth')
subdir('lib-dns-client')
subdir('lib-ssl-iostream')
subdir('lib-master')
subdir('lib-charset')
subdir('lib-json')
subdir('lib-dcrypt')
subdir('lib-dict')
subdir('lib-http')
subdir('lib-oauth2')
subdir('lib-sasl')
subdir('lib-auth-client')
subdir('lib-login')
